### ISSUE TITLE
Jump in a point of video

### ISSUE THREAD

**Issue by gborasio** [amittkSharma/react-video-player-extended#52]
Hi is there a way to jump in a particular part of the video ?
For example i extract a list of tpic with initial timestamp and i want to click on topic list and see the point in the video.

**Comment by amittkSharma** [comment]
Hi, 

Yes one can do it, by creating the markers using the following interface

export interface Marker {
  id: number
  time: number
  title: string
}

Here you can provide the timestamp and topic as the title,  which will start appearing in the video timeline. The id is the unique identifier. 
Then one jumps back and forth between the markers, using the video controls.

Please let me know if that solved your use case. Otherwise, we can discuss your use case in more detail.

Thanks and regards
